In [2]:
#Import Libreries 
from selenium import webdriver
import pandas as pd
import selenium
import time
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
import requests
import re

#### Q1- Write a python program which searches all the product under a particular product vertical from www.amazon.in. The product verticals to be searched will be taken as input from user. For e.g. If user input is ‘guitar’. Then search for guitars.
#### Q2- In the above question, now scrape the following details of each product listed in first 3 pages of your search results and save it in a dataframe and csv. In case if any product vertical has less than 3 pages in search results then scrape all the products available under that product vertical. Details to be scraped are: "Brand Name", "Name of the Product", "Rating", "No. of Ratings", "Price", "Return/Exchange", "Expected Delivery", "Availability", "Other Details" and “Product URL”. In case, if any of the details are missing for any of the product then replace it by “-“.

In [35]:
driver = webdriver.Chrome("chromedriver.exe")     
url = "https://www.amazon.in/"
driver.get(url)

time.sleep(2)
product = input('Enter the product name : ')

Enter the product name : guitar

In [36]:
search = driver.find_element_by_id("twotabsearchtextbox")    
search.clear()                                              
search.send_keys(product)                                  
searchbutton = driver.find_element_by_xpath('//div[@class="nav-search-submit nav-sprite"]/span/input')     
searchbutton.click()

In [37]:
product_urls = []

for page in range(0,3):
    url=driver.find_elements_by_xpath('//a[@class="a-link-normal a-text-normal"]')      
    for i in url:
        product_urls.append(i.get_attribute("href"))                        
    nxt_button=driver.find_element_by_xpath("//li[@class='a-normal'][1]/a")    
    nxt_button.click()
    time.sleep(2)
len(product_urls)

156

In [39]:

Brand = []   
Name = []
Rating = []
NoOfRatings = []
Price = []
Return = []
deliveryexpected = []
Availability = [] 
OtherDetails = []

for url in product_urls:
    driver.get(url)
    try:
        brand = driver.find_element_by_xpath('//a[@id="bylineInfo"]')      
        Brand.append(brand.text)
    except NoSuchElementException:
        Brand.append('-')    

    try:
        name = driver.find_element_by_id('productTitle')      
        Name.append(name.text)
    except NoSuchElementException:
        Name.append('-')

    try:
        rating = driver.find_element_by_xpath('//span[@class="a-size-base a-nowrap"]//span')  
        Rating.append(rating.text)
    except NoSuchElementException:
        Rating.append('-')


    try:
        noRating = driver.find_element_by_id('acrCustomerReviewText')  
        NoOfRatings.append(noRating.text)
    except NoSuchElementException:
        NoOfRatings.append('-')


    try:
        price = driver.find_element_by_xpath('//td[@class="a-span12"]')  
        Price.append(price.text)
    except NoSuchElementException:
        Price.append('-')


    try:
        preturn = driver.find_element_by_xpath('//a[@class="a-size-small a-link-normal a-text-normal"]')  
        Return.append(preturn.text)
    except NoSuchElementException:
        Return.append('-')

        
    try:
        delivery= driver.find_element_by_xpath('//span[@class="a-color-error"]')  
        deliveryexpected.append(delivery.text)
    except NoSuchElementException:
         deliveryexpected.append('-')

    try:
        Pavailibity= driver.find_element_by_xpath('//span[@class="a-size-medium a-color-success"]')  
        Availability.append(Pavailibity.text)
    except NoSuchElementException:
        Availability.append('-')
 
    try:
        Details= driver.find_element_by_xpath('//ul[@class="a-unordered-list a-vertical a-spacing-mini"]')  
        OtherDetails.append(Details.text)
    except NoSuchElementException:
        OtherDetails.append('-')

time.sleep(3)

In [40]:
prodt=pd.DataFrame({})
prodt['Brand']=Brand
prodt['Name']=Name
prodt['Rating']=Rating
prodt['No of ratings']=NoOfRatings
prodt['Price']=Price
prodt['Return/Exchange']=Return
prodt['Delivery Expected']=deliveryexpected
prodt['Availability']=Availability
prodt['Other Details']=OtherDetails
prodt['URL']=product_urls
prodt

,Brand,Name,Rating,No of ratings,Price,Return/Exchange,Delivery Expected,Availability,Other Details,URL
0,Visit the JUAREZ Store,"Juârez Acoustic Guitar, 38 Inch Cutaway, 038C ...",3.9 out of 5,"11,625 ratings","₹2,649.00",Pay on Delivery,-,In stock.,"Black Glossy Finish, Number of Frets: 18, Acou...",https://www.amazon.in/Juarez-Acoustic-Cutaway-...
1,Brand: Intern,"Intern INT-38C Acoustic Guitar Kit, With Bag, ...",3.9 out of 5,"6,341 ratings","₹2,290.00",Pay on Delivery,-,In stock.,Great looks with an innovative design to produ...,https://www.amazon.in/Intern-INT-38C-Acoustic-...
2,Visit the JUAREZ Store,"Juarez JRZ38C Acoustic Guitar, 38 Inch Cutaway...",4 out of 5,"3,967 ratings","₹2,649.00",Pay on Delivery,,-,"Black glossy finish, number of frets: 18, acou...",https://www.amazon.in/JUAREZ-JRZ38C-Acoustic-S...
3,Visit the JUAREZ Store,JUAREZ JRZ38C Right Handed Acoustic Guitar wit...,4 out of 5,"2,603 ratings","₹2,649.00",Pay on Delivery,-,In stock.,Number of Frets: 18\nAcoustic guitar with stra...,https://www.amazon.in/JUAREZ-JRZ38C-Acoustic-N...
4,Brand: Intern,Intern INT-38C Acoustic Guitar Kit (Sunburst) ...,3.9 out of 5,"6,341 ratings","₹2,390.00",Pay on Delivery,-,In stock.,Great looks with an innovative design to produ...,https://www.amazon.in/Intern-INT-38C-Acoustic-...
...,...,...,...,...,...,...,...,...,...,...
151,Brand: Jixing,"Jixing JXNG-BLK,Black Acoustic Guitar with Sta...",3.8 out of 5,740 ratings,"₹3,499.00",Pay on Delivery,-,In stock.,The product comes in a proper packaging\nThis ...,https://www.amazon.in/Jixing-JXNG-BLK-Acoustic...
152,Brand: Intern,Intern INT-38C-NT-G Right Handed Acoustic Guit...,4 out of 5,879 ratings,"₹2,590.00",Pay on Delivery,-,In stock.,38 inches cutaway revolutionary design and con...,https://www.amazon.in/Intern-INT-38C-NT-G-Guit...
153,Brand: Martin Smith,Martin Smith W-101-N-PK Acoustic Guitar Super ...,4.3 out of 5,"3,288 ratings","₹6,349.00",Pay on Delivery,,In stock.,Steel strung full scale neck\nSlim line contou...,https://www.amazon.in/Martin-Smith-W-101-N-PK-...
154,Brand: K J ENTERPRISE,K J ENTERPRISE Guitar Toys for Kids 4-String A...,-,-,₹749.00,7 Days Replacement,-,In stock.,4 String which are tune-able. A very good toy ...,https://www.amazon.in/ENTERPRISE-Guitar-4-Stri...
155,Visit the JUAREZ Store,JUAREZ Fiésta 41 Inch Acoustic Guitar Cutaway ...,2.7 out of 5,8 ratings,"₹4,009.00",Pay on Delivery,-,In stock.,"Glossy finish, Number of frets - 21, 41 Inch A...",https://www.amazon.in/JUAREZ-Acoustic-Rosewood...

#### 3-Write a python program to access the search bar and search button on images.google.com and scrape 100 images each for keywords ‘fruits’, ‘cars’ and ‘Machine Learning’.

In [41]:

driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(3)
url = "https://images.google.com/"
driver.get(url)
search = driver.find_element_by_xpath('//*[@id="sbtc"]/div/div[2]/input')   
search.send_keys("fruits")      
search_button = driver.find_element_by_xpath('//*[@id="sbtc"]/button')   
search_button.click()

In [43]:
for a in range(5):
    driver.execute_script("window.scrollBy(0,300)")
images = driver.find_elements_by_xpath('//img[@class="rg_i Q4LuWd"]')
imgUrl = []
for image in images:
    source= image.get_attribute('src')
    if source is not None:
        if(source[0:4] == 'http'):
            imgUrl.append(source)
                  
for i in range(len(imgUrl)):
    if i >= 100:
        break
    print("Downloading {0} of {1} images" .format(i, 100))
    response= requests.get(imgUrl[i])
    file = open(r"E:\imp project\Fruits\Fruits"+str(i)+".jpg", "wb")
    file.write(response.content)

Downloading 0 of 100 images
Downloading 1 of 100 images
Downloading 2 of 100 images
Downloading 3 of 100 images
Downloading 4 of 100 images
Downloading 5 of 100 images
Downloading 6 of 100 images
Downloading 7 of 100 images
Downloading 8 of 100 images
Downloading 9 of 100 images
Downloading 10 of 100 images
Downloading 11 of 100 images
Downloading 12 of 100 images
Downloading 13 of 100 images
Downloading 14 of 100 images
Downloading 15 of 100 images
Downloading 16 of 100 images
Downloading 17 of 100 images
Downloading 18 of 100 images
Downloading 19 of 100 images
Downloading 20 of 100 images
Downloading 21 of 100 images
Downloading 22 of 100 images
Downloading 23 of 100 images
Downloading 24 of 100 images
Downloading 25 of 100 images
Downloading 26 of 100 images
Downloading 27 of 100 images
Downloading 28 of 100 images
Downloading 29 of 100 images
Downloading 30 of 100 images
Downloading 31 of 100 images
Downloading 32 of 100 images
Downloading 33 of 100 images
Downloading 34 of 100 images
Downloading 35 of 100 images
Downloading 36 of 100 images
Downloading 37 of 100 images
Downloading 38 of 100 images
Downloading 39 of 100 images
Downloading 40 of 100 images
Downloading 41 of 100 images
Downloading 42 of 100 images
Downloading 43 of 100 images
Downloading 44 of 100 images
Downloading 45 of 100 images
Downloading 46 of 100 images
Downloading 47 of 100 images
Downloading 48 of 100 images
Downloading 49 of 100 images
Downloading 50 of 100 images
Downloading 51 of 100 images
Downloading 52 of 100 images
Downloading 53 of 100 images
Downloading 54 of 100 images
Downloading 55 of 100 images
Downloading 56 of 100 images
Downloading 57 of 100 images
Downloading 58 of 100 images
Downloading 59 of 100 images
Downloading 60 of 100 images
Downloading 61 of 100 images
Downloading 62 of 100 images
Downloading 63 of 100 images
Downloading 64 of 100 images
Downloading 65 of 100 images
Downloading 66 of 100 images
Downloading 67 of 100 images
Downloading 68 of 100 images
Downloading 69 of 100 images
Downloading 70 of 100 images
Downloading 71 of 100 images
Downloading 72 of 100 images
Downloading 73 of 100 images
Downloading 74 of 100 images
Downloading 75 of 100 images
Downloading 76 of 100 images
Downloading 77 of 100 images
Downloading 78 of 100 images
Downloading 79 of 100 images
Downloading 80 of 100 images
Downloading 81 of 100 images
Downloading 82 of 100 images
Downloading 83 of 100 images
Downloading 84 of 100 images
Downloading 85 of 100 images
Downloading 86 of 100 images
Downloading 87 of 100 images
Downloading 88 of 100 images
Downloading 89 of 100 images
Downloading 90 of 100 images
Downloading 91 of 100 images
Downloading 92 of 100 images
Downloading 93 of 100 images
Downloading 94 of 100 images
Downloading 95 of 100 images
Downloading 96 of 100 images
Downloading 97 of 100 images
Downloading 98 of 100 images
Downloading 99 of 100 images

##### Cars

In [61]:
#Specify Search URL
driver = webdriver.Chrome("chromedriver.exe")   
search_url = "https://www.google.com/search?q={q}&tbm=isch&tbs=sur%3Afc&hl=en&ved=0CAIQpwVqFwoTCKCa1c6s4-oCFQAAAAAdAAAAABAC&biw=1251&bih=568"
driver.get(search_url.format(q='cars'))

In [52]:
#Scroll to the end of the page
driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
time.sleep(5)#sleep_between_interactions

In [62]:

driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(3)
url = "https://images.google.com/"
driver.get(url)
search = driver.find_element_by_xpath('//*[@id="sbtc"]/div/div[2]/input')   
search.send_keys("cars")      
search_button = driver.find_element_by_xpath('//*[@id="sbtc"]/button')   
search_button.click()

In [64]:
for a in range(9):
    driver.execute_script("window.scrollBy(0,2000)")
images = driver.find_elements_by_xpath('//img[@class="rg_i Q4LuWd"]')
imgUrl = []
for image in images:
    source= image.get_attribute('src')
    if source is not None:
        if(source[0:4] == 'http'):
            imgUrl.append(source)
                  
for i in range(len(imgUrl)):
    if i >= 100:
        break
    print("Downloading {0} of {1} images" .format(i, 100))
    response= requests.get(imgUrl[i])
    file = open(r"E:\imp project\Cars\Car"+str(i)+".jpg", "wb")
    file.write(response.content)

Downloading 0 of 100 images
Downloading 1 of 100 images
Downloading 2 of 100 images
Downloading 3 of 100 images
Downloading 4 of 100 images
Downloading 5 of 100 images
Downloading 6 of 100 images
Downloading 7 of 100 images
Downloading 8 of 100 images
Downloading 9 of 100 images
Downloading 10 of 100 images
Downloading 11 of 100 images
Downloading 12 of 100 images
Downloading 13 of 100 images
Downloading 14 of 100 images
Downloading 15 of 100 images
Downloading 16 of 100 images
Downloading 17 of 100 images
Downloading 18 of 100 images
Downloading 19 of 100 images
Downloading 20 of 100 images
Downloading 21 of 100 images
Downloading 22 of 100 images
Downloading 23 of 100 images
Downloading 24 of 100 images
Downloading 25 of 100 images
Downloading 26 of 100 images
Downloading 27 of 100 images

In [71]:
driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(3)
url = "https://images.google.com/"
driver.get(url)
search = driver.find_element_by_xpath('//*[@id="sbtc"]/div/div[2]/input')   
search.send_keys("machine learning")      
search_button = driver.find_element_by_xpath('//*[@id="sbtc"]/button')   
search_button.click()

In [74]:
for a in range(9):
    driver.execute_script("window.scrollBy(0,2000)")
images = driver.find_elements_by_xpath('//img[@class="rg_i Q4LuWd"]')
imgUrl = []
for image in images:
    source= image.get_attribute('src')
    if source is not None:
        if(source[0:4] == 'http'):
            imgUrl.append(source)
                  
for i in range(len(imgUrl)):
    if i >= 100:
        break
    print("Downloading {0} of {1} images" .format(i, 100))
    response= requests.get(imgUrl[i])
    file = open(r"E:\imp project\Machine learning\machine learning"+str(i)+".jpg", "wb")
    file.write(response.content)

Downloading 0 of 100 images
Downloading 1 of 100 images
Downloading 2 of 100 images
Downloading 3 of 100 images
Downloading 4 of 100 images
Downloading 5 of 100 images
Downloading 6 of 100 images
Downloading 7 of 100 images
Downloading 8 of 100 images
Downloading 9 of 100 images
Downloading 10 of 100 images
Downloading 11 of 100 images
Downloading 12 of 100 images
Downloading 13 of 100 images
Downloading 14 of 100 images
Downloading 15 of 100 images
Downloading 16 of 100 images
Downloading 17 of 100 images
Downloading 18 of 100 images
Downloading 19 of 100 images
Downloading 20 of 100 images
Downloading 21 of 100 images
Downloading 22 of 100 images
Downloading 23 of 100 images
Downloading 24 of 100 images
Downloading 25 of 100 images
Downloading 26 of 100 images
Downloading 27 of 100 images
Downloading 28 of 100 images
Downloading 29 of 100 images
Downloading 30 of 100 images
Downloading 31 of 100 images
Downloading 32 of 100 images
Downloading 33 of 100 images
Downloading 34 of 100 images
Downloading 35 of 100 images
Downloading 36 of 100 images
Downloading 37 of 100 images
Downloading 38 of 100 images
Downloading 39 of 100 images
Downloading 40 of 100 images
Downloading 41 of 100 images
Downloading 42 of 100 images
Downloading 43 of 100 images
Downloading 44 of 100 images
Downloading 45 of 100 images
Downloading 46 of 100 images
Downloading 47 of 100 images
Downloading 48 of 100 images
Downloading 49 of 100 images
Downloading 50 of 100 images
Downloading 51 of 100 images
Downloading 52 of 100 images
Downloading 53 of 100 images
Downloading 54 of 100 images
Downloading 55 of 100 images
Downloading 56 of 100 images
Downloading 57 of 100 images
Downloading 58 of 100 images
Downloading 59 of 100 images
Downloading 60 of 100 images
Downloading 61 of 100 images
Downloading 62 of 100 images
Downloading 63 of 100 images
Downloading 64 of 100 images
Downloading 65 of 100 images
Downloading 66 of 100 images
Downloading 67 of 100 images
Downloading 68 of 100 images
Downloading 69 of 100 images
Downloading 70 of 100 images
Downloading 71 of 100 images
Downloading 72 of 100 images
Downloading 73 of 100 images
Downloading 74 of 100 images
Downloading 75 of 100 images
Downloading 76 of 100 images
Downloading 77 of 100 images
Downloading 78 of 100 images
Downloading 79 of 100 images
Downloading 80 of 100 images
Downloading 81 of 100 images
Downloading 82 of 100 images
Downloading 83 of 100 images
Downloading 84 of 100 images
Downloading 85 of 100 images
Downloading 86 of 100 images
Downloading 87 of 100 images
Downloading 88 of 100 images
Downloading 89 of 100 images
Downloading 90 of 100 images
Downloading 91 of 100 images
Downloading 92 of 100 images
Downloading 93 of 100 images
Downloading 94 of 100 images
Downloading 95 of 100 images
Downloading 96 of 100 images
Downloading 97 of 100 images
Downloading 98 of 100 images
Downloading 99 of 100 images

#### Q4. Write a python program to search for a smartphone(e.g.: Oneplus Nord, pixel 4A, etc.) on www.flipkart.com and scrape following details for all the search results displayed on 1st page. Details to be scraped: “Brand Name”, “Smartphone name”, “Colour”, “RAM”, “Storage(ROM)”, “Primary Camera”, “Secondary Camera”, “Display Size”, “Display Resolution”, “Processor”, “Processor Cores”, “Battery Capacity”, “Price”, “Product URL”. Incase if any of the details is missing then replace it by “- “. Save your results in a dataframe and CSV.

In [77]:
driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(1)
driver.get('https://www.flipkart.com/')
time.sleep(2)    
search = driver.find_element_by_xpath('//*[@id="container"]/div/div[1]/div[1]/div[2]/div[2]/form/div/div/input')   
search.clear()               
search.send_keys("Oneplus Nord")       
search_button = driver.find_element_by_xpath('//button[@class="L0Z3Pu"]')   
search_button.click()

In [79]:
# Fetching urls of phones coming on 1st page
flip_urls = []
urls = driver.find_elements_by_xpath('//a[@class="_1fQZEK"]')
for url in urls:
    flip_urls.append(url.get_attribute("href"))

In [84]:
driver = webdriver.Chrome("chromedriver.exe") 
import requests
geo_url = 'http://maps.googleapis.com/maps/api/geocode/json'

In [85]:

# Import pandas package  
import pandas as pd 
import numpy as np
    
# Define a dictionary containing  data 
data = {'City':['Bangalore', 'Mumbai', 'Chennai', 'Delhi']} 
    
# Convert the dictionary into DataFrame 
df = pd.DataFrame(data) 
    
# Observe the result 
df

        City
0  Bangalore
1     Mumbai
2    Chennai
3      Delhi

#### * Q5. Write a program to scrap geospatial coordinates (latitude, longitude) of a city searched on google maps.

In [86]:
from geopy.exc import GeocoderTimedOut
from geopy.geocoders import Nominatim

longitude = []
latitude = []
   

def findGeocode(city):

    try:
        geolocator = Nominatim(user_agent="your_app_name")
          
        return geolocator.geocode(city)
      
    except GeocoderTimedOut:
          
        return findGeocode(city)    

for i in (df["City"]):
      
    if findGeocode(i) != None:
           
        loc = findGeocode(i)
          
        latitude.append(loc.latitude)
        longitude.append(loc.longitude)
        
    else:
        latitude.append(np.nan)
        longitude.append(np.nan)

In [87]:

df["Longitude"] = longitude
df["Latitude"] = latitude
  
df

        City  Longitude   Latitude
0  Bangalore  77.591300  12.979120
1     Mumbai  72.877393  19.075990
2    Chennai  80.270186  13.083694
3      Delhi  77.221939  28.651718

#### 7. Write a program to scrap all the available details of best gaming laptops from digit.in

In [88]:
url ='https://www.digit.in/top-products/best-gaming-laptops-40.html'  #set url here
driver.get(url)                  
Titles_tags=driver.find_elements_by_xpath("//div[@class='right-container']//h3")
Titles_tags
#Now we will run for loop to find all data
titles=[]              #empty tag 
for i in Titles_tags:      
    titles.append(i.text)

titles

['ALIENWARE AREA 51M R2',
 'ALIENWARE M15 R3',
 'ASUS ROG STRIX SCAR 15',
 'ASUS ROG ZEPHYRUS G14',
 'LENOVO LEGION 5I',
 'ASUS ROG ZEPHYRUS DUO 15',
 'ACER ASPIRE 7 GAMING']

In [91]:
Title_tags8=driver.find_elements_by_xpath("//div[@class='Section-center']//P")
Title_tags8
#Now we will run for loop to find all data
Description8=[]              #empty tag 
for i in Title_tags8:      
    Description8.append(i.text)
    
Title_tags1=driver.find_elements_by_xpath("//div[@class='right-container']//div[@class='Spcs-details']//tr[3]")
Title_tags1
#Now we will run for loop to find all data
Description1=[]              #empty tag 
for i in Title_tags1:      
    Description1.append(i.text)


Title_tags2=driver.find_elements_by_xpath("//div[@class='right-container']//div[@class='Spcs-details']//tr[4]")
Title_tags2
#Now we will run for loop to find all data
Description2=[]              #empty tag 
for i in Title_tags2:      
    Description2.append(i.text)

Description2

Title_tags2=driver.find_elements_by_xpath("//div[@class='right-container']//div[@class='Spcs-details']//tr[5]")
Title_tags2
#Now we will run for loop to find all data
Description3=[]              #empty tag 
for i in Title_tags2:      
    Description3.append(i.text)

Description3

Title_tags2=driver.find_elements_by_xpath("//div[@class='right-container']//div[@class='Spcs-details']//tr[6]")
Title_tags2
#Now we will run for loop to find all data
Description4=[]              #empty tag 
for i in Title_tags2:      
    Description4.append(i.text)

Title_tags2=driver.find_elements_by_xpath("//div[@class='right-container']//div[@class='Spcs-details']//tr[7]")
Title_tags2
#Now we will run for loop to find all data
Description5=[]              #empty tag 
for i in Title_tags2:      
    Description5.append(i.text)



Title_tags2=driver.find_elements_by_xpath("//div[@class='right-container']//div[@class='Spcs-details']//tr[8]")
Title_tags2
#Now we will run for loop to find all data
Description6=[]              #empty tag 
for i in Title_tags2:      
    Description6.append(i.text)

Title_tags2=driver.find_elements_by_xpath("//div[@class='right-container']//div[@class='Spcs-details']//tr[9]")
Title_tags2
#Now we will run for loop to find all data
Description7=[]              #empty tag 
for i in Title_tags2:      
    Description7.append(i.text)

In [93]:

DT=pd.DataFrame({})
DT['Title']=titles

DT['os']=Description1
DT['Display']=Description2
DT['Processor']=Description3
DT['Memory']=Description4
DT['Weight']=Description5
DT['Graphics Processor']=Description6

DT

,Title,os,Display,Processor,Memory,Weight,Graphics Processor
0,ALIENWARE AREA 51M R2,OS : Windows 10 Home,"Display : 17.3"" (1920 x 1080)",Processor : 10th Generation Intel® Core™ i7-10...,Memory : 1 TB SSD/16 GBGB DDR4,Weight : 4.1,Dimension : 27.65 x 402.6 x 319.14
1,ALIENWARE M15 R3,OS : Windows 10 Home,"Display : 15.6"" (3840 x 2160)",Processor : 10th Generation Intel® Core™ i9-10...,Memory : 1 TB SSD/16 GBGB DDR4,Weight : NA,Dimension : NA
2,ASUS ROG STRIX SCAR 15,OS : Windows 10 Home,"Display : 15.6"" (1920 x 1080)",Processor : AMD Ryzen™ 9 5900HX | 3.3 GHz,Memory : 1 TB SSD/16 GBGB DDR4,Weight : 2.30,Dimension : 35.4 x 25.9 x 2.26
3,ASUS ROG ZEPHYRUS G14,OS : Windows 10 Home,"Display : 14"" (1920 x 1080)",Processor : AMD 3rd Generation Ryzen 9 | 3.3 GHz,Memory : 1 TB SSD/16 GBGB DDR4,Weight : 1.65,Dimension : 32.5 x 22.1 x 1.8
4,LENOVO LEGION 5I,OS : Windows 10 Pro,"Display : 15.6"" (1920 x 1080)",Processor : 10th Generation Intel® Core™ i5-10...,Memory : 1 TB SSD/16 GBGB DDR4,Weight : 2.3,Dimension : 363.06 x 259.61 x 23.57
5,ASUS ROG ZEPHYRUS DUO 15,OS : Windows 10,"Display : 15.6"" (3840 x 1100)",Processor : Intel Core i7 10th Gen 10875H | NA,Memory : 512 GB SSD/4 GBGB DDR4,Weight : 2.4,Dimension : 268.30 x 360.00 x 20.90
6,ACER ASPIRE 7 GAMING,OS : Windows 10 Home,"Display : 15.6"" (1920 x 1080)",Processor : AMD Ryzen™ 5-5500U hexa-core | NA,Memory : 512 GB SSD/8 GBGB DDR4,Weight : 2.15,Dimension : 2.29 x 36.3 x 25.4

#### 8 Write a python program to scrape the details for all billionaires from www.forbes.com. Details to be scrapped: “Rank”, “Name”, “Net worth”, “Age”, “Citizenship”, “Source”, “Industry”.¶

In [94]:
driver = webdriver.Chrome("chromedriver.exe") 
url ='https://www.forbes.com/real-time-billionaires/#7d435b853d78'  #set url here
driver.get(url)

In [95]:

Name=driver.find_elements_by_xpath("//td[@class='name']")
Name
#Now we will run for loop to find all data
Name1=[]              #empty tag 
for i in Name:      
    Name1.append(i.text)
    
Networth=driver.find_elements_by_xpath("//td[@class='Net Worth']")
Networth
#Now we will run for loop to find all data
Net_worth=[]              #empty tag 
for i in Networth:      
    Net_worth.append(i.text)

age1=driver.find_elements_by_xpath("//td[@class='age']")
age1
#Now we will run for loop to find all data
age=[]              #empty tag 
for i in age1:      
    age.append(i.text)

source1=driver.find_elements_by_xpath("//td[@class='source']")
source1
#Now we will run for loop to find all data
source=[]              #empty tag 
for i in source1:      
    source.append(i.text)

Country=driver.find_elements_by_xpath("//td[@class='Country/Territory']")
Country
#Now we will run for loop to find all data
Country1=[]              #empty tag 
for i in Country:      
    Country1.append(i.text)

In [96]:

people=pd.DataFrame({})

people['Name']=Name1
people['Net worth']=Net_worth
people['Age']=age
people['Industry']=source
people['Country']=Country1

people

,Name,Net worth,Age,Industry,Country
0,Bernard Arnault & family,$192.4 B,72,LVMH,France
1,Jeff Bezos,$192.4 B,57,Amazon,United States
2,Elon Musk,$179.4 B,50,"Tesla, SpaceX",United States
3,Bill Gates,$131.6 B,65,Microsoft,United States
4,Mark Zuckerberg,$128.2 B,37,Facebook,United States
5,Larry Page,$115.2 B,48,Google,United States
6,Larry Ellison,$112.6 B,76,software,United States
7,Sergey Brin,$111.5 B,47,Google,United States
8,Warren Buffett,$101.0 B,90,Berkshire Hathaway,United States
9,Francoise Bettencourt Meyers & family,$90.2 B,68,L'Oréal,France
10,Steve Ballmer,$83.6 B,65,Microsoft,United States
11,Amancio Ortega,$78.6 B,85,Zara,Spain
12,Mukesh Ambani,$77.4 B,64,diversified,India
13,Carlos Slim Helu & family,$73.3 B,81,telecom,Mexico
14,Zhong Shanshan,$69.7 B,66,"beverages, pharmaceuticals",China
15,Jim Walton,$65.1 B,73,Walmart,United States
16,Alice Walton,$64.7 B,71,Walmart,United States
17,Rob Walton,$64.3 B,76,Walmart,United States
18,Phil Knight & family,$60.5 B,83,Nike,United States
19,Michael Bloomberg,$59.0 B,79,Bloomberg LP,United States
20,François Pinault & family,$56.5 B,84,luxury goods,France
21,MacKenzie Scott,$56.0 B,51,Amazon,United States
22,Gautam Adani & family,$53.1 B,59,"infrastructure, commodities",India
23,Michael Dell,$49.5 B,56,Dell computers,United States
24,Robin Zeng,$48.9 B,52,batteries,Hong Kong

#### 6. Write a program to scrap details of all the funding deals for second quarter (i.e. July 20 – September 20) from trak.in.

In [98]:
driver=webdriver.Chrome("chromedriver.exe") 
url = "https://trak.in/"
driver.get(url)
button = driver.find_element_by_xpath('//li[@id="menu-item-51510"]/a').get_attribute('href')
driver.get(button)

In [103]:
# do click on funding deals
button = driver.find_element_by_xpath('//li[@id="menu-item-51510"]/a').get_attribute('href')
driver.get(button)

Date = []
StartupName= []
IndustryVertical= []
SubVertical= []
Location= []
Investor = []
InvestmentType= []
Amount= []
for i in range(48,51):
    date = driver.find_elements_by_xpath('//table[@id="tablepress-{}"]/tbody/tr/td[2]'.format(i))
    for d in date:
        Date.append(d.text)
        
    sn = driver.find_elements_by_xpath('//table[@id="tablepress-{}"]/tbody/tr/td[3]'.format(i))
    for n in sn:
        StartupName.append(n.text)
    
    indVer = driver.find_elements_by_xpath('//table[@id="tablepress-{}"]/tbody/tr/td[4]'.format(i))
    for n in indVer:
        IndustryVertical.append(n.text)
    
    subvert = driver.find_elements_by_xpath('//table[@id="tablepress-{}"]/tbody/tr/td[5]'.format(i))
    for s in subvert:
        SubVertical.append(s.text)

    loc = driver.find_elements_by_xpath('//table[@id="tablepress-{}"]/tbody/tr/td[6]'.format(i))
    for l in loc:
        Location.append(l.text)
    
    investor = driver.find_elements_by_xpath('//table[@id="tablepress-{}"]/tbody/tr/td[7]'.format(i))
    for n in investor:
        Investor.append(n.text)
       
    investment = driver.find_elements_by_xpath('//table[@id="tablepress-{}"]/tbody/tr/td[8]'.format(i))
    for n in investment:
        InvestmentType.append(n.text)  

    amt = driver.find_elements_by_xpath('//table[@id="tablepress-{}"]/tbody/tr/td[9]'.format(i))
    for a in amt:
        Amount.append(a.text)

In [104]:

dt=pd.DataFrame({})
dt['Date']=Date
dt['StartupName']=StartupName
dt['Industry/Vertical']=IndustryVertical
dt['Sub-Vertical']=SubVertical
dt['Location']=Location
dt['Investor']=Investor
dt['Investment Type']=InvestmentType
dt['Amount']=Amount

dt

,Date,StartupName,Industry/Vertical,Sub-Vertical,Location,Investor,Investment Type,Amount
0,15/07/2020,Flipkart,E-commerce,E-commerce,Bangalore,Walmart Inc,M&A,"1,200,000,000"
1,16/07/2020,Vedantu,EduTech,Online Tutoring,Bangalore,Coatue Management,Series D,"100,000,000"
2,16/07/2020,Crio,EduTech,Learning Platform for Developers,Bangalore,021 Capital,pre-Series A,"934,160"
3,14/07/2020,goDutch,FinTech,Group Payments,Mumbai,"Matrix India,Y Combinator, Global Founders Cap...",Seed,"1,700,000"
4,13/07/2020,Mystifly,Airfare Marketplace,"Ticketing, Airline Retailing, and Post-Ticketi...",Singapore and Bangalore,Recruit Co. Ltd.,pre-Series B,"3,300,000"
5,09/07/2020,JetSynthesys,Gaming and Entertainment,Gaming and Entertainment,Pune,Adar Poonawalla and Kris Gopalakrishnan.,Venture-Series Unknown,"400,000"
6,10/07/2020,gigIndia,Marketplace,"Crowd Sourcing, Freelance",Pune,Incubate Fund India and Beyond Next Ventures,pre-Series A,"974,200"
7,15/07/2020,PumPumPum,Automotive Rental,Used Car-leasing platform,Gurgaon,Early Adapters Syndicate,Seed,"292,800"
8,14/07/2020,FLYX,OTT Player,Streaming Social Network,New York and Delhi,"Raj Mishra, founder of AIT Global Inc",pre-Seed,"200,000"
9,13/07/2020,Open Appliances Pvt. Ltd.,Information Technology,Internet-of-Things Security Solutions,Bangalore,Unicorn India Ventures,Venture-Series Unknown,"500,000"
10,15/08/2020,Practo,HealthTech,Health care and Wellness,Bangalore,A1A Company,Series F,"32,000,000"
11,13/08/2020,Medlife,E-commerce,Online Pharmacy,Bangalore,Prasid Uno Family Trust and SC Credit Fund,,"23,000,000"
12,13/08/2020,HungerBox,FoodTech,Online Food Delivery Service,Bangalore,"One97, Sabre Partners Trust, Pratithi Investme...",Series D1,"1,560,000"
13,04/08/2020,Dunzo,Hyper-local Logistics,Online Delivery Services,Bangalore,Existing Backers,In Progress,"30,000,000"
14,11/08/2020,Terra.do,EduTech,"Online Climate School, E-learning","Stanford, California,","Stanford Angels and Entrepreneurs (India), BEE...",Seed,"1,400,000"
15,12/08/2020,Classplus,EduTech,"E-learning, Online Tutoring",Noida,Falcon Edge,In Progress,"upto 15,000,000"
16,14/08/2020,Niyo,FinTech,Financial Services,Bangalore,Niyo Solutions Inc.,,"6,000,000"
17,10/08/2020,ZestMoney,FinTech,Financial Services,Bangalore,Primrose Hills Ventures,,"10,670,000"
18,07/08/2020,FreshToHome,E-commerce,Food Delivery,Bangalore,Ascent Capital,Venture,"16,200,000"
19,13/08/2020,Eduvanz,FinTech,Financial Services,Mumbai,"Sequoia India, Unitus",Series A,"5,000,000"
20,08/09/2020,Byju’s,EduTech,Online Tutoring,Bangalore,"Silver Lake, Tiger Global, General Atlantic an...",Private Equity,"500,000,000"
21,12/09/2020,mCaffeine,Personal Care,Skincare & Haircare,Mumbai,"Amicus Capital Private Equity I LLP, Amicus Ca...",Series B,"3,000,000"
22,09/09/2020,Qshala,EduTech,Online Curiosity Platform for Kids,Bangalore,Rainmatter Capital,Angel,"370,000"
23,02/09/2020,Winzo,Online Gaming,Online Gaming,New Delhi,"Kalaari Capital Partners, IndigoEdge Managemen...",Series B,"15,500,000"
24,09/09/2020,Hippo Video,Video Customer Experience(CX) Platform,Video Customer Experience(CX) Platform,"Newark, Delaware, United States of Amercia","Alpha Wave Incubation, Exfinity Venture Partne...",Series A,"4,500,000"
25,07/09/2020,Melorra,E-commerce,Online Jewelry Store,Bangalore,"Shadow Holdings, Lightbox.",Debt Financing,"upto 8,900,000"
26,07/09/2020,1mg,E-commerce,Online Pharmacy,Gurgaon,"Gaja Capital, Tata Capital, Partners Group",In Progress,"100,000,000"
27,31/08/2020,mfine,HealthTech,On-Demand Healthcare Services,Bangalore,Caretech Pte Inc,Series B,"5,400,000"
28,31/08/2020,Apna,Human Resources,Recruitment Platform,Bangalore,Lightspeed India and Sequoia Capital India,Series A,"8,000,000"
29,03/09/2020,Railofy,Transportation,WL & RAC protection platform,Mumbai,Chiratae Ventures,Seed,"950,000"

#### 9. Write a program to extract at least 500 Comments, Comment upvote and time when comment was posted from any YouTube Video.

In [34]:
import time
from selenium.webdriver import Chrome
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

In [38]:
data=[]

with Chrome(executable_path='chromedriver.exe') as driver:
    wait = WebDriverWait(driver,15)
    driver.get("https://www.youtube.com/watch?v=kuhhT_cBtFU&t=2s")

    for item in range(5): 
        wait.until(EC.visibility_of_element_located((By.TAG_NAME, "body"))).send_keys(Keys.END)
        time.sleep(15)

    for comment in wait.until(EC.presence_of_all_elements_located((By.CSS_SELECTOR, "#content"))):
        data.append(comment.text)   
 #note range will set for 500 comment 250

In [39]:
import pandas as pd   
df = pd.DataFrame(data, columns=['comment'])
df.head()

                                             comment
0  IN\nSKIP NAVIGATION\nSIGN IN\n#CNN #News\nBody...
1
2  Bodycam video released by the Atlanta Police D...
3  I always wonder why CNN never shows the whole ...
4  Good parenting: “teaches about good and bad pe...

#### Q10. Write a python program to scrape a data for all available Hostels from https://www.hostelworld.com/ in “London” location. You have to scrape hostel name, distance from city centre, ratings, total reviews, overall reviews, privates from price, dorms from price, facilities and property description

In [10]:
driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(3)

url = "https://www.hostelworld.com/"
driver.get(url)

In [12]:
search_loc = driver.find_element_by_id('search-input-field')
search_loc.send_keys("London")
time.sleep(2)

In [13]:
london = driver.find_element_by_xpath('/html/body/div[1]/div/div/div[1]/div[1]/div/div[2]/div[4]/div/div[2]/div/div[1]/div/div/ul/li[2]/div')
london.click()
time.sleep(2)

In [14]:
search_btn = driver.find_element_by_id('search-button')
search_btn.click()

In [15]:
Hostel_Name = []
Distance = []
overall_review = []
total_reviews = []
facilities = []
price = []
Rating = []
property_description = []

while(True):
    
    names = driver.find_elements_by_xpath('//h2[@class="title title-6"]')
    for name in names:
        Hostel_Name.append(name.text)
        
    dis = driver.find_elements_by_xpath('//span[@class="description"]')
    for d in dis:
        Distance.append(d.text)
 
    review = driver.find_elements_by_xpath('//div[@class="keyword"]//span')
    for r in review:
        overall_review.append(r.text)
   
    t_review = driver.find_elements_by_xpath('//div[@class="reviews"]')
    for tr in t_review:
        total_reviews.append(tr.text)

    service = driver.find_elements_by_xpath('//div[@class="facilities-label facilities"]')
    for s in service:
        facilities.append(s.text)

    prices = driver.find_elements_by_xpath('//div[@class="price-col"]')
    for p in prices:
        price.append(p.text)
        
    try:
        next_button = driver.find_element_by_xpath('//div[@class="pagination-item pagination-next"]')
        next_button.click()
    except:
        break

In [25]:

dt=pd.DataFrame({})
dt['Hostel Name']=Hostel_Name
dt['Startup Name']=Distance
dt['Overall Review']=overall_review[3:]
dt['Total reviews']=total_reviews
dt['Facilities']=facilities
dt['Privates From']=Privates_From
dt

,Hostel Name,Startup Name,Overall Review,Total reviews,Facilities,Privates From
0,St Christopher's Village,Hostel - 1.8km from city centre,Fabulous,10821 Total Reviews,Free WiFi\nFollows Covid-19 sanitation guidance,Privates From\nRs3863
1,Generator London,Hostel - 3km from city centre,Very Good,6734 Total Reviews,Free WiFi\nFollows Covid-19 sanitation guidance,Privates From\nRs8175
2,Safestay London Kensington Holland Park,Hostel - 5.9km from city centre,Fabulous,1076 Total Reviews,Free WiFi,Privates From\nRs5125
3,"PubLove @ The Crown, Battersea",Hostel - 4.7km from city centre,Good,207 Total Reviews,Free WiFi\nFollows Covid-19 sanitation guidance,Privates From\nRs8280
4,247london Hostel and Private Rooms,Hostel - 8.2km from city centre,No Rating,443 Total Reviews,Free WiFi,Privates From\nRs5278
...,...,...,...,...,...,...
82,23 Matheson Road,Bed and Breakfast - 6.2km from city centre,No Rating,6 Total Reviews,,Privates From\nRs3932
83,Park Hotel Essex,Hotel - 24.1km from city centre,No Rating,108 Total Reviews,Free Breakfast\nFollows Covid-19 sanitation gu...,Privates From\nRs3829
84,Cranbrook Hotel,Hotel - 14.8km from city centre,No Rating,58 Total Reviews,Free Breakfast\nFollows Covid-19 sanitation gu...,Privates From\nRs3622
85,St. Athans,Bed and Breakfast - 2.9km from city centre,No Rating,234 Total Reviews,Free WiFi\nFollows Covid-19 sanitation guidance,Privates From\nRs4622
86,Aron Guest House,Bed and Breakfast - 13.1km from city centre,No Rating,26 Total Reviews,Free WiFi,Privates From\nRs6727